# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-07 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogCreateTime', models.DateTimeField(auto_now_add=True)),
                ('blogModifyTime', models.DateTimeField(auto_now=True)),
                ('blogTitle', models.CharField(max_length=50, verbose_name='博客标题')),
                ('blogIntro', models.CharField(max_length=100, verbose_name='博客简介')),
                ('blogContent', models.TextField(verbose_name='博客内容')),
                ('blogPopupNum', models.IntegerField(verbose_name='点赞数')),
                ('blogFavoNum', models.IntegerField(verbose_name='收藏数')),
                ('blogCover', models.ImageField(default='/media/1.jpg', upload_to='cover/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
