# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-07 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_blogauthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogFavoNum',
            field=models.IntegerField(default=0, verbose_name='收藏数'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blogPopupNum',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
