# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-07 12:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200307_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogCreateTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 7, 12, 26, 0, 949070), null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blogModifyTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 7, 12, 26, 0, 949154), null=True),
        ),
    ]
