# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-07 12:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200307_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogCreateTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 7, 20, 28, 20, 716280), null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blogModifyTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 7, 20, 28, 20, 716367), null=True),
        ),
    ]
