# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-07 12:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200307_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogCreateTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 7, 12, 35, 20, 258695, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blogModifyTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 7, 12, 35, 20, 258782, tzinfo=utc)),
        ),
    ]
