# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-08 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='commentLikeNum',
            field=models.IntegerField(default=0),
        ),
    ]
